### ISSUE TITLE
curl.h file not available in wiced studio. 

### ISSUE THREAD

**Issue by pavithragowda** [ubidots/ubidots-c#2] opened 2018-01-30 05:52 UTC
Hello developers, 

i am trying to send the data to ubidots in wiced studio. 
 i have downloaded the ubidots c sdk from github. and added  those code to my project. 
curl.h file is not available in wiced studio. i was trying to add the curl.h file but that did not work.

can anyone help on this?

Regards, 
Pavithra

**Comment by jotathebest** [comment] 2018-01-30 18:10
Closed as this is not a bug.

Inside the README is specified:

"_Ubidots depends on libjansson and libcurl_"

You have to install those libraries inside your development environment and include them in your headers. If your environment does not have them you can also compile them using the instructions from here:

- Libcurl: https://curl.haxx.se/docs/install.html
- Libjansson: https://jansson.readthedocs.io/en/1.1/gettingstarted.html

Regards

**Closed** 2018-01-30 18:11 UTC
